
version: "3.7"
services:
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./mqtt_config:/mosquitto/config:rw
      - ./mqtt_data:/mosquitto/data:rw
      - ./mqtt_log:/mosquitto/log:rw
  influxdb2:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb2
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb2
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'  

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:
  influxdb:
  grafana_storage: {}

networks:
  default:
    name: metrics
