{
 "title": "Indoor Weather",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outside Pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pressurepa" } },
     "targets": [
      {
       "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"weather\" and r._field == \"pressure\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
      }
     ]
    }
   ]
  },
  { "title": "Indoor Air Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CO2 - Current",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"co2\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "aqi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"us_aqi\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Indoor Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"temp\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Indoor Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"humidity\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Outdoor Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"weather\" and r._field == \"temperature\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"co2\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "AQI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "AQI" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"us_aqi\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "PM 1.0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"pm_1\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "PM 2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"pm_2_5\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "PM 10.0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"pm_10\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  { "title": "Indoor Weather", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Indoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"temp\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Indoor Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"humidity\")\r\n        |> aggregateWindow(every: ${interval}, fn: mean)"
    }
   ]
  },
  {
   "title": "Outside Weather",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"weather\" and r._field == \"temperature\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Outside Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"weather\" and r._field == \"humidity\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Compensation Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"mh_temp\")\r\n    |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  }
 ]
}